### ISSUE TITLE
Enhancement: Fix to various compilation problems

### ISSUE THREAD

**Issue by DANI002428** [CryBitDev/Sonic.exe-source-1.5#2]
Hi, it's me again and there is a problem compiling to Mac, Windows 32 Bits, Android etc.

One of these solutions told me that it is to erase traces of MP4 but that would remove the cinematics and when I did that, I was presented with many errors when starting the game on the home screen.

Now:

To add cutscenes to the game without getting the MP4 compatibility error is to do them through Webm together with Txt and ogg, that is the only way I can compile and work correctly, hopefully take my suggestion and do it also for devices of 32 Bit, Mac and HTML5.

**Comment by CryBitDev** [comment]
Support for multiple platforms is still in the works, glad you found the solution!
